### ISSUE TITLE
Juju bootstrap fails on Azure

### ISSUE THREAD

**Issue by jiasir** [juju/juju#1541]
I am in China, Using Azure of China Edition. This is my `environments.yaml`:
```
environments:
    # https://juju.ubuntu.com/docs/config-azure.html
    azure:
        type: azure

        # location specifies the place where instances will be started,
        # for example: West US, North Europe.
        #
        location: North CN

        # The following attributes specify Windows Azure Management
        # information. See:
        # http://msdn.microsoft.com/en-us/library/windowsazure
        # for details.
        #
        management-subscription-id: xxx
        management-certificate-path: /Users/Taio/.juju/azure.pem

        # storage-account-name holds Windows Azure Storage info.
        #
        storage-account-name: xxx
```

When I execute `juju bootstrap --show-log`, The flowing error output:
```
TaiodeMacBook-Pro:.juju Taio$ juju bootstrap --show-log
2015-02-05 03:45:56 INFO juju.cmd supercommand.go:37 running juju [1.21.1-yosemite-amd64 gc]
Bootstrap failed, cleaning up the environment.
2015-02-05 03:46:00 ERROR juju.cmd supercommand.go:323 there was an issue examining the environment: authentication failed

Please ensure the Azure subscription ID and certificate you have specified
are correct. You can obtain your subscription ID from the "Settings" page
in the Azure management console, where you can also upload a new certificate
if necessary.
```

I am ensure the Azure subscription ID and certificate is correct. If the Azure API different from China Azure version?

**Comment by mattyw** [comment]
@jiasir thanks for your report. Sorry it hasn't been responded to yet. I'll see what I can find out for you

**Comment by sinzui** [comment]
Juju requires the storage to be in the same location as the location of your env. Is your storage in that location? Can you create storage in North CN? Most people cannot create storage in China, so bootstrapping there is impossible.

**Comment by jiasir** [comment]
@sinzui Thanks! I can create storage in North CN, if the API different from EN-US?

**Comment by dimitern** [comment]
@jiasir Now that 1.22.0 stable is out, can you upgrade and retry? But first, try this. I think the problem might be solved by changing the value of `location:` to `China North`. Despite the virtually non existent details about Azure China, including the names of the regions (in English, at least), I found some places quote "China North" as a region name.

**Comment by jiasir** [comment]
@dimitern Thank you so much! Mabe it worked. I changed the value of `location:` to `China North`. The output are:
```
localhost:.juju Taio$ juju bootstrap --show-log
2015-03-25 05:29:13 INFO juju.cmd supercommand.go:37 running juju [1.21.1-yosemite-amd64 gc]
2015-03-25 05:29:15 INFO juju.network network.go:106 setting prefer-ipv6 to false
2015-03-25 05:29:15 INFO juju.utils http.go:59 hostname SSL verification enabled
2015-03-25 05:29:16 INFO juju.utils http.go:59 hostname SSL verification enabled
2015-03-25 05:29:17 INFO juju.utils http.go:59 hostname SSL verification enabled
2015-03-25 05:29:17 INFO juju.utils http.go:59 hostname SSL verification enabled
Bootstrap failed, destroying environment
2015-03-25 05:29:21 ERROR juju.cmd supercommand.go:323 failed to bootstrap environment: no cost data for region "China North"
```
The output different from `authentication failed`, but my Azure subscription ID was expired. I can not testing it. and it output is correct. Thanks! @dimitern

**Comment by jiasir** [comment]
@mattyw Thanks! It worked. I have changed the value of `location:` to `China North` not `North CN`. But my Azure subscription ID was expired, when I return I will testing it.

**Comment by jiasir** [comment]
@dimitern The value of `location: China North` is correct, I found out the source:
```
// getEndpoint returns the simplestreams endpoint to use for the given Azure
// location (e.g. West Europe or China North).
func getEndpoint(location string) string {
// Simplestreams uses the management-API endpoint for the image, not
// the base managent API URL.
return gwacl.GetEndpoint(location).ManagementAPI()
}
```

**Comment by rcarmo** [comment]
I'm having a similar issue with a fresh install (using brew to run juju and juju-quickstart from a Mac). I've been using Azure for a few months and decided to try juju as an alternative to the current CLI tools, and so far it hasn't been very rewarding (I've been poring over the docs and forums, and got no joy or useful hints).

Here's my YAML config:

<pre>
# This file has been generated by juju quickstart v2.1.1
# at 2015-06-16 13:44:32 UTC.

default: TEST-Azure
environments:
  TEST-Azure:
    admin-secret: changeme
    default-series: trusty
    image-stream: released
    location: West Europe
    management-certificate-path: /Users/rcarmo/.blu/cert.pem
    management-subscription-id: 926d8725-XXXX-XXXX-XXXX-93106b621352
    storage-account-name: juju
    type: azure
</pre>

And here's the output:

<pre>
unexpected:~ rcarmo$ rm -rf .juju/environments
unexpected:~ rcarmo$  juju bootstrap --show-log
2015-06-16 13:57:13 INFO juju.cmd supercommand.go:37 running juju [1.24.0-yosemite-amd64 gc]
2015-06-16 13:57:16 INFO juju.network network.go:194 setting prefer-ipv6 to false
Bootstrapping environment "TEST-Azure"
2015-06-16 13:57:19 INFO juju.environs.tools tools.go:86 reading tools with major.minor version 1.24
Bootstrap failed, destroying environment
2015-06-16 13:57:27 ERROR juju.cmd.juju common.go:43 the environment could not be destroyed: cannot clean up storage: failed to delete container juju-TEST-Azure-private: Azure request failed: OutOfRangeInput - One of the request inputs is out of range.
RequestId:492c0958-0001-002f-553c-a8e40a000000
Time:2015-06-16T13:56:14.8393980Z (http code 400: Bad Request)
2015-06-16 13:57:27 ERROR juju.cmd supercommand.go:430 failed to bootstrap environment: Juju cannot bootstrap because no tools are available for your environment.
You may want to use the 'agent-metadata-url' configuration setting to specify the tools location.
</pre>

The storage account is empty (and on the same region, and I can create containers and blobs inside it manually, etc.). I'm a bit miffed at the "no tools are available for your environment" message, especially since I tried to find accurate docs on the agent-metadata-url config setting and had very little luck on figuring out what it should be or how to debug it...

**Comment by jiasir** [comment]
@rcarmo Yes, the similar issue.

**Comment by rcarmo** [comment]
Well, I’ve gone and set up a fresh Ubuntu 14.04.2 LTS VM, did an apt-get install juju (which installed 1.3), set up my config as above, and it now fails with:

ERROR PUT request failed: BadRequest - XML Schema validation error in network configuration at line 31,18. (http code 400: Bad Request)

My best guess is that the Azure provisioning layer in this version is outdated and that it cannot talk to the current Azure APIs - perhaps the XML config file structure has changed, or there’s a missing field somewhere, but either way being unable to use the stable version of juju (running inside Ubuntu) should be enough to have someone look at this sooner, no?

**Comment by OMSKremer** [comment]
Same Problem here. Fresh Ubuntu 14.04.2 LTS.

root@CW-0000-TEST:~# juju bootstrap
Bootstrapping environment "azure"
Starting new instance for initial state server
Bootstrap failed, destroying environment
ERROR failed to bootstrap environment: PUT request failed: BadRequest - XML Schema validation error in network configuration at line 24,18. (http code 400: Bad Request)

**Comment by anastasiamac** [comment]
Last communication on this thread has been from a year ago.

Since then we have vastly improved experience in currently supported version 1.25 and completely changed Azure SDK on Juju 2.0.

We track our bug in launchpad. Please file bugs on https://bugs.launchpad.net/juju-core/ if you are experiencing any failures.
