### ISSUE TITLE
[1.24-beta2] [jujuclient] [status] Occasional RPC AllWatcher Next failure

### ISSUE THREAD

**Issue by johnsca** [juju/juju#2318]
`juju-deployer` output w/ debug (shows RPC request and error): http://pastebin.ubuntu.com/11116671/
`juju status` output: http://pastebin.ubuntu.com/11116673/

This doesn't happen on every deploy, but when it does, it happens consistently thereafter for that environment, even after the mentioned service is removed.  It is also not always the same service (for this bundle), but it always has the 'u#' prefix.

**Comment by anastasiamac** [comment]
There have been significant changes since 1.24 in AllWatcher. Our currently supported version is 1.25. Juju 2.0 - on master tip with several betas for early trial - has even more exciting improvements.

We track our bugs on launchpad - https://bugs.launchpad.net/juju-core. Please file bugs there for quicker resolution.
