### ISSUE TITLE
ERROR failed to bootstrap environment: cannot start bootstrap instance: no matching tools available

### ISSUE THREAD

**Issue by nitinrpatil** [juju/juju#3606]
Hi,

I have configured a MAAS Server (on VM) with two nodes. When both the nodes are PXE booted & their status on MAAS Web interface becomes "Ready", I give the following commands:

root@VM0002:~# mkdir ~/.juju/sync-tools
root@VM0002:~# juju sync-tools -e maas --destination="~/.juju/sync-tools"

After that, when I give the command-
root@VM0002:~# juju bootstrap -e maas --upload-tools=true --metadata-source="/root/.juju/sync-tools"

The following error is coming:

Bootstrapping environment "maas"
Starting new instance for initial state server
Launching instance
WARNING no architecture was specified, acquiring an arbitrary node
Bootstrap failed, destroying environment
ERROR failed to bootstrap environment: cannot start bootstrap instance: no matching tools available 

What could be the possible reason for this failure? Please suggest any solution...

**Comment by dooferlad** [comment]
@nitinrpatil 

After setting up your MAAS and putting your MAAS credentials in ~/.juju/environments.yaml, to bootstrap an environment simply run:

```bash
juju switch maas
juju bootstrap --upload-tools=true
```

This should start a VM, PXE boot it and set it up as machine 0 for Juju. At that point you can add machines and deploy charms. This requires that you have power control set up for your MAAS nodes, but that is a very worthwhile step. If you are running Linux there is a little tool to help set up KVM machines in MAAS here https://github.com/dooferlad/kvm_maas 

You only need to use --metadata-source if your MAAS doesn't have internet access, in which case you need to set --metadata-source to the location you downloaded your tools to, i.e. "~/.juju/sync-tools". This isn't something I have tried myself, but that seems to be what the docs are saying.

If this doesn't answer your question I recommend subscribing to https://lists.ubuntu.com/mailman/listinfo/juju or using another method listed on https://jujucharms.com/community to get help because it will reach more people quickly.

**Comment by nitinrpatil** [comment]
@dooferlad 
Thanks for the reply!

Actually, my nodes are not running on VM, only the MAAS Server is running on VM.

Earlier, i had tried with the simple "juju bootstrap" command, but it was failing to download tools from https://streams.canonical.com/juju/tools/releases/juju-1.24.6-trusty-i386.tgz with the errors:
"curl: (7) Failed to connect to streams.canonical.com port 443: Connection timed out"
"ERROR failed to bootstrap environment: subprocess encountered error code 1"

Therefore, first I downloaded the tools using command "juju sync-tools" successfully. Then, by using "juju bootstrap" command with the options "--upload-tools" and "--metadata-source", i got this error:
"ERROR failed to bootstrap environment: cannot start bootstrap instance: no matching tools available"

I am still unclear about this error, since the tools were already available at given location.

**Comment by kat-co** [comment]
Hi, sorry for the long delay. We usually track issues here: https://bugs.launchpad.net/juju-core

Is this still an issue for you?

**Comment by nitinrpatil** [comment]
Hi, my issue has been resolved after re-installing the MAAS server on a physical machine instead of a VM.
Thanks for the reply!

**Comment by aluguri-tarun** [comment]
hello Nithin,
can you please share me the instuctioins you have followed to install maas and juju, because i keep getting the following error.
url: (7) Failed to connect to streams.canonical.com port 443: Connection timed out"
"ERROR failed to bootstrap environment: subprocess encountered error code 1"
Thanks in advance!!

**Comment by nitinrpatil** [comment]
@aluguri-tarun sorry, i have not documented the instructions. You can refer to the MAAS official documentation (http://maas.ubuntu.com/docs/index.html) for instructions.

**Comment by aluguri-tarun** [comment]
@nitinrpatil  okay!! thanks for the reply!! :)
