### ISSUE TITLE
ERROR failed to create config

### ISSUE THREAD

**Issue by ghost** [juju/juju#5669]
New error with new update to 2.0-beta9-xenial-amd64 triggered when trying to create a new model.

```shell
ERROR failed to create config: creating config from values failed: name: expected string, got nothing
```

**Comment by wurde** [comment]
Supplying some random 'name:' config via the --config option seems to do the trick. The current usage of the juju CLI says juju add-model should already get that name: option from the command.

```shell
Usage: juju add-model [options] <model name>
```

Current state of things:

```shell
juju add-model --config name=devenv
#=> ERROR failed to create config: creating config from values failed: name: expected string, got nothing

juju add-model devenv --config name=devenv
#=> added model "devenv"
```

**Comment by anastasiamac** [comment]
This should have been fixed in the following betas. We are currently at beta14.

Since <model name> is a positional argument, as long as you provide it in the command, it should work. 

If you are experiencing further failures, please file a bug on https://bugs.launchpad.net/juju-core
We track our bug there.
