### ISSUE TITLE
Expose leadership over websocket API?

### ISSUE THREAD

**Issue by petevg** [juju/juju#6591]
At present, if a charm depends on the leadership layer, and one wants to know whether a deployed unit is the leader, one can invoke FullStatus via the Client Facade over the websocket api, and then dig through the resulting json object.

This ticket requests that leadership be added to the deltas that get passed over the websocket connection, so that libraries like python-libjuju can keep track of leadership in their model, along with everything else, without requiring a separate FullStatus invocation.

This currently affects the matrix testing suite (https://github.com/juju-solutions/matrix), which cares about leadership, and currently needs to send a flurry of additional queries over the api, and/or cache potentially outdated information, in order to track leadership.

**Comment by johnsca** [comment]
To clarify, the issue is that the unit deltas that come in on the AllWatcher does not contain the leadership flag but otherwise contains all or more of the fields from UnitStatus.  This means that leadership is the only field that requires an explicit separate call to one of FullStatus, ApplicationStatus, or UnitStatus.

**Comment by mitechie** [comment]
Thanks, this makes sense and is something we'll work to get into a release as some bug work.

**Comment by anastasiamac** [comment]
As we track Juju 2.x issues and suggestions through launchpad, I've created https://bugs.launchpad.net/juju/+bug/1643691
